version: '3'
services:
  web:
    build:
      context: docker/
    volumes:
      - ./src/:/var/www/
    environment:
    - VIRTUAL_HOST=goenchoxetkar.localhost
    ports:
      - "8080:80"